# Generated by Django 2.2 on 2021-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_reads_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_Listed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_wants', models.ManyToManyField(related_name='wants_posts', to='great_reads_app.User')),
            ],
        ),
    ]
