# Generated by Django 2.2 on 2021-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_reads_app', '0002_books_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_listed',
            name='book_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books_listed',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
