# Generated by Django 2.2 on 2021-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_reads_app', '0003_auto_20210606_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_listed',
            name='book_quote',
            field=models.TextField(null=True),
        ),
    ]
